// Auth Action Types
export const AUTH_ACTION_TYPES = {
  SET_CHECKED_AUTH: "auth/SET_CHECKED_AUTH",
  SET_CURRENT_USER: "auth/SET_CURRENT_USER",
  SET_ERROR: "auth/SET_ERROR",
  SET_IS_LOADING: "auth/SET_IS_LOADING",
  START_INITIALIZING_AUTH: "auth/START_INITIALIZING_AUTH",
  START_OAUTH: "auth/START_OAUTH",
  LOGOUT_USER: "auth/LOGOUT_USER",
};
