// Document Action Types
export const DOCUMENT_ACTION_TYPES = {
  SET_DOCUMENTS: "document/SET_DOCUMENTS",
  SET_IS_LOADING: "document/SET_IS_LOADING",
  START_FETCHING_DOCUMENTS: "document/START_FETCHING_DOCUMENTS",
  START_UPDATING_DOCUMENT: "document/START_UPDATING_DOCUMENT",
  START_DELETING_DOCUMENT: "document/START_DELETING_DOCUMENT",
  START_SYNCING_DOCUMENTS: "document/START_SYNCING_DOCUMENTS",
};
