// Document Action Types
export const DOCUMENT_ACTION_TYPES = {
  SET_DOCUMENTS: "document/SET_DOCUMENTS",
  SET_IS_LOADING: "document/SET_IS_LOADING",
  SET_LOADING_TYPE: "document/SET_LOADING_TYPE",
  START_FETCHING_DOCUMENTS: "document/START_FETCHING_DOCUMENTS",
  START_ADDING_DOCUMENT: "document/START_ADDING_DOCUMENT",
  START_UPDATING_DOCUMENT: "document/START_UPDATING_DOCUMENT",
  START_DELETING_DOCUMENT: "document/START_DELETING_DOCUMENT",
};
