// Ui Action Types
export const UI_ACTION_TYPES = {
  SET_SIDE_BAR_VISIBILITY: "ui/SET_SIDE_BAR_VISIBILITY",
  SET_THEME: "ui/SET_THEME",
  SET_EDITOR_FULLSCREEN: "ui/SET_EDITOR_FULLSCREEN",
  SET_SCROLL_WITH: "ui/SET_SCROLL_WITH",
  SET_IS_LOADING: "ui/SET_IS_LOADING",
};
