// Ui Action Types
export const UI_ACTION_TYPES = {
  SET_SIDE_BAR_VISIBILITY: "ui/SET_SIDE_BAR_VISIBILITY",
  SET_EDITOR_FULLSCREEN: "ui/SET_EDITOR_FULLSCREEN",
  SET_SCROLL_WITH: "ui/SET_SCROLL_WITH",
  SET_IS_LOADING: "ui/SET_IS_LOADING",
  SET_LOADING_TYPE: "ui/SET_LOADING_TYPE",
  SET_ERROR: "ui/SET_ERROR",
  START_FETCHING_UI_SETTINGS: "ui/START_FETCHING_UI_SETTINGS",
  START_ADDING_UI_SETTINGS: "ui/START_ADDING_UI_SETTINGS",
  START_UPDATING_UI_SETTINGS: "ui/START_UPDATING_UI_SETTINGS",
};
